openapi: "3.0.3"
info:
  title: Controle de Ponto API
  version: "1.0"
components:
  schemas:
    momento:
      type: object
      description: O momento da batida
      properties:
        dataHora:
          description: Data e hora da batida
          type: string
          example: "2018-08-22T08:00:00"
    mensagem:
      type: object
      properties:
        mensagem:
          type: string
paths:
  /batidas:
    post:
      summary: Bater ponto
      description: |
        Registrar um horário da jornada diária de trabalho
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/momento'
      responses:
        "201":
          description: |
            Created
        "400":
          description: |
            Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mensagem'
              examples:
                Data e hora em formato inválido:
                  value:
                    mensagem: Data e hora em formato inválido
                Campo obrigatório não informado:
                  value:
                    mensagem: Campo obrigatório não informado
        "403":
          description: |
            Forbiden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mensagem'
              examples:
                apenas 4 horários por dia:
                  value:
                    mensagem: Apenas 4 horários podem ser registrados por dia
                mínimo 1 hora de almoço:
                  value:
                    mensagem: Deve haver no mínimo 1 hora de almoço
                sábado e domingo não são permitidos:
                  value:
                    mensagem: Sábado e domingo não são permitidos como dia de trabalho
        "409":
          description: |
            Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mensagem'
              examples:
                Horários já registrado:
                  value:
                    mensagem: Horários já registrado